version: 0.2
env:
  variables:
    S3_BUCKET: "whatsinstandard"
    PACKAGE: "github.com/aws-samples-lambda-go-samples"
phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      - env
